### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by 0CCULTIST** [ZL-Audio/ZLEComp#29]
Hi. I'm aware this plugin is deprecated, but releasing a final Linux build would be much appreciated for obvious reasons.

**Comment by zsliu98** [comment]
I am afraid that this plugin is unusable on Linux.
This plugin is experimental. The reason for the deprecation is that the code has tons of problems (which I did not realize until the equalization plugin). I have tested the plugin on GitHub Linux runners before. It crashed about 50% of all tests. Therefore, the final binary is likely to crash DAWs sooner or later. Finally, I decided to rework a new version.
